version: '3'
services:
    gitlab:
      image: gitlab/gitlab-ce:latest
      hostname: 'localhost'
      environment:
        TZ: 'Asia/Ho_Chi_Minh'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'localhost'
          gitlab_rails['time_zone'] = 'Asia/Ho_Chi_Minh'
      ports:
        - '8080:80'
        - '443:443'
        - '1022:22'
      volumes:
        - ./gitlab/config:/etc/gitlab
        - ./gitlab/logs:/var/log/gitlab
        - ./gitlab/data:/var/opt/gitlab
      restart: always

    git-runner:
      image: gitlab/gitlab-runner:latest
      restart: always
      links:
        - gitlab

    postgresql:
      image: postgres:latest
      environment:
        POSTGRES_USER: gitlab
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: gitlabhq_production
      restart: always
      volumes:
        - ./postgresql/data:/var/lib/postgresql/data
      ports:
        - 5433:5432
