version: '3'
services:
    gitlab:
      image: gitlab/gitlab-ce:15.8.1
      hostname: 'localhost'
      ports:
        - '18891:80'
        - '18892:443'
        - '18893:22'
      volumes:
        - /gitlab/config:/etc/gitlab
        - /gitlab/logs:/var/log/gitlab
        - /gitlab/data:/var/opt/gitlab
      restart: always

    git-runner:
      image: gitlab/gitlab-runner:15.8.1
      restart: always
      links:
        - gitlab

    postgresql:
      image: postgres:13.8
      environment:
        POSTGRES_USER: gitlab
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: gitlabhq_production
      restart: always
      volumes:
        - /gitlab/postgresql/data:/var/lib/postgresql/data
      ports:
        - 5433:5432
